### ISSUE TITLE
[Feature] 메인페이지

### ISSUE THREAD

**Issue by spiderq2697** [JNU-econovation/collusic-new#14]
### 컴포넌트 설명
요청작 목록을 볼 수 있다.

- [x] 요청분야에 따른 요청작 컴포넌트
- [x] #32 
- [x] #33 

### 디자인
![image](https://user-images.githubusercontent.com/65025333/147729222-9b580f80-8507-4b58-8608-d01fda958973.png)

**Comment by SingTheCode** [comment]
#15
